package com.sms.auth.dto;

public enum ErrorCode {
    SUCCESS,

    // Authentication errors
    INVALID_TOKEN,
    TOKEN_REPLAY_DETECTED,
    UNAUTHORIZED,

    DUPLICATE_EMAIL,
    DUPLICATE_PHONE,

    INVALID_PASSWORD,
    WEAK_PASSWORD,
    PASSWORD_TOO_SHORT,
    PASSWORD_MISSING_UPPERCASE,
    PASSWORD_MISSING_LOWERCASE,
    PASSWORD_MISSING_DIGIT,
    PASSWORD_MISSING_SPECIAL,
    PASSWORD_TOO_COMMON,
    
    INVALID_PHONE_FORMAT,
    INVALID_EMAIL_FORMAT,
    INVALID_CREDENTIALS,
    INVALID_LANGUAGE,
    RATE_LIMIT_EXCEEDED,
    ACCOUNT_LOCKED,
    SESSION_EXPIRED,

    PHOTO_SIZE_EXCEEDED,
    INVALID_PHOTO_FORMAT,
    PROFILE_UPDATE_FAILED,

    CORRUPTED_IMAGE,
    VALIDATION_ERROR,
    INTERNAL_ERROR
}
