package com.sms.auth.dto;

public enum ErrorCode {
    SUCCESS,
    DUPLICATE_EMAIL,
    DUPLICATE_PHONE,
    INVALID_PASSWORD,
    INVALID_PHONE_FORMAT,
    INVALID_EMAIL_FORMAT,
    INVALID_CREDENTIALS,
    INVALID_LANGUAGE,
    RATE_LIMIT_EXCEEDED,
    ACCOUNT_LOCKED,
    SESSION_EXPIRED,
    INTERNAL_ERROR
}
